name: Add issues to form0 project

on:
  issues:
    types:
      - opened
      - reopened
      - transferred

jobs:
  add-to-project:
    uses: paqu-io/.github/.github/workflows/add-form0-issue-to-project.yml@main
    secrets: inherit